site_name: MEV REST API
site_description: Documentation for the MEV RESTful API

repo_url: https://github.com/web-mev/mev-backend

markdown_extensions:
 - toc:
    anchorlink: True
 - admonition
 - codehilite
 - mkautodoc

theme: readthedocs
extra_css: [style.css]

nav:
 - Home: 'index.md'
 - Architecture: 'general_architecture.md'
 - Installation and Setup: 
   - Preliminaries: 'install.md'
   - MEV cluster setup: 'mev_cluster_setup.md'
   - Configuration: 'setup_configuration.md'
   - Cromwell job runner setup: 'cromwell_setup.md'
 - API: 
   - Intro and core concepts: 'api.md'
   - Data Structures:
      - Attributes: 'attributes.md'
      - Observations and Features: 'elements.md'
      - ObservationSet and FeatureSets: 'observation_and_feature_sets.md'
      - Workspaces: 'workspaces.md'
      - Workspace metadata: 'metadata.md'
      - Resources: 
         - General info: 'resources.md'
         - Resource types: 'resource_types.md'
         - Resource metadata: 'resource_metadata.md'
 - Authentication: 'auth.md'
 - Operation concepts: 'operations.md'
 - Creating new analyses/operations: 'creating_analyses.md'
 - Workflow and analysis concepts: 'example_workflow.md'

